import { Locale, LocalizedText, pickLocalizedText } from "@/lib/locale";

const ADMIN_TEXT_MAP: Record<string, LocalizedText> = {
    "保存中": { "zh-CN": "保存中", en: "Saving" },
    "已保存": { "zh-CN": "已保存", en: "Saved" },
    "未变更": { "zh-CN": "未变更", en: "No changes" },
    "取消": { "zh-CN": "取消", en: "Cancel" },
    "关闭": { "zh-CN": "关闭", en: "Close" },
    "编辑知识条目": { "zh-CN": "编辑知识条目", en: "Edit knowledge" },
    "知识内容（全文）": { "zh-CN": "知识内容（全文）", en: "Knowledge content" },
    "请输入知识内容...": { "zh-CN": "请输入知识内容...", en: "Enter knowledge content..." },
    "字符": { "zh-CN": "字符", en: "chars" },
    "ID（只读）": { "zh-CN": "ID（只读）", en: "ID (read-only)" },
    "个 scope": { "zh-CN": "个 scope", en: "scopes" },
    "条关系": { "zh-CN": "条关系", en: "relations" },
    "条命中": { "zh-CN": "条命中", en: "hits" },
    "全文检索": { "zh-CN": "全文检索", en: "Full-text search" },
    "取消全选": { "zh-CN": "取消全选", en: "Clear all" },
    "全选": { "zh-CN": "全选", en: "Select all" },
    "暂无知识条目": { "zh-CN": "暂无知识条目", en: "No knowledge items" },
    "已选": { "zh-CN": "已选", en: "Selected" },
    "条": { "zh-CN": "条", en: "items" },
    "取消选择": { "zh-CN": "取消选择", en: "Clear selection" },
    "批量删除": { "zh-CN": "批量删除", en: "Bulk delete" },
    "搜索节点... 匹配的节点会高亮放大": { "zh-CN": "搜索节点... 匹配的节点会高亮放大", en: "Search nodes... matches are highlighted" },
    "清除": { "zh-CN": "清除", en: "Clear" },
    "实体总数": { "zh-CN": "实体总数", en: "Total entities" },
    "关系总数": { "zh-CN": "关系总数", en: "Total relations" },
    "热门实体 Top 10": { "zh-CN": "热门实体 Top 10", en: "Top 10 entities" },
    "按关联度排序": { "zh-CN": "按关联度排序", en: "Ranked by connectivity" },
    "关系": { "zh-CN": "关系", en: "links" },
    "近期日志": { "zh-CN": "近期日志", en: "Recent logs" },
    "暂无日志": { "zh-CN": "暂无日志", en: "No logs yet" },
    "project scope 已纳入记忆页管理": { "zh-CN": "project scope 已纳入记忆页管理", en: "Project scopes are tracked here" },
    "模型绑定": { "zh-CN": "模型绑定", en: "Model bindings" },
    "记忆提取、Embedding 与 Rerank 都从这里指定，并最终写回统一的 models.json 事实源。": { "zh-CN": "记忆提取、Embedding 与 Rerank 都从这里指定，并最终写回统一的 models.json 事实源。", en: "Bind extraction, embedding, and rerank models here. All changes write back to the canonical models.json source." },
    "抽取模型 (LLM)": { "zh-CN": "抽取模型 (LLM)", en: "Extraction model (LLM)" },
    "抽取温度 (Temperature)": { "zh-CN": "抽取温度 (Temperature)", en: "Extraction temperature" },
    "低值（0~0.3）使提取结果更稳定，高值更有创意": { "zh-CN": "低值（0~0.3）使提取结果更稳定，高值更有创意", en: "Lower values (0-0.3) keep extraction stable. Higher values add more variation." },
    "嵌入模型 (Embedding)": { "zh-CN": "嵌入模型 (Embedding)", en: "Embedding model" },
    "全局检索重排模型": { "zh-CN": "全局检索重排模型", en: "Global reranker" },
    "无 (None)": { "zh-CN": "无 (None)", en: "None" },
    "RAG 检索协同": { "zh-CN": "RAG 检索协同", en: "RAG retrieval" },
    "控制 recall 的召回方式、Top-K、阈值和被动注入行为，让模型绑定和检索策略一起生效。": { "zh-CN": "控制 recall 的召回方式、Top-K、阈值和被动注入行为，让模型绑定和检索策略一起生效。", en: "Control recall strategy, top-k, thresholds, and passive injection so retrieval and model bindings work together." },
    "Artifact Explorer 加载失败": { "zh-CN": "Artifact Explorer 加载失败", en: "Artifact Explorer load failed" },
    "请选择左侧 artifact 卡片。": { "zh-CN": "请选择左侧 artifact 卡片。", en: "Select an artifact card from the left." },
    "请选择语言模型以进行实体与偏好抽取": { "zh-CN": "请选择语言模型以进行实体与偏好抽取", en: "Choose an LLM for entity and preference extraction" },
    "用于读取对话记录并萃取出知识图谱实体、用户偏好的基础模型。": { "zh-CN": "用于读取对话记录并萃取出知识图谱实体、用户偏好的基础模型。", en: "Base model used to extract knowledge graph entities and user preferences from conversations." },
    "请选择向量嵌入模型": { "zh-CN": "请选择向量嵌入模型", en: "Choose an embedding model" },
    "用于生成用户查询和记忆条目的向量特征，支持语义相似度检索。": { "zh-CN": "用于生成用户查询和记忆条目的向量特征，支持语义相似度检索。", en: "Used to embed queries and memory items for semantic retrieval." },
    "请选择重排序模型（可选）": { "zh-CN": "请选择重排序模型（可选）", en: "Choose a reranker (optional)" },
    "主要服务 memory / RAG 的二阶段精排；若扩展生态或桌面候选没有单独指定，也会回退使用这里的全局重排模型。": { "zh-CN": "主要服务 memory / RAG 的二阶段精排；若扩展生态或桌面候选没有单独指定，也会回退使用这里的全局重排模型。", en: "Used for second-stage reranking in memory and RAG. Extensions and desktop candidates fall back here when no dedicated reranker is bound." },
    "平衡混合检索": { "zh-CN": "平衡混合检索", en: "Balanced hybrid" },
    "语义优先": { "zh-CN": "语义优先", en: "Semantic first" },
    "关键词优先": { "zh-CN": "关键词优先", en: "Keyword first" },
    "请选择 recall 策略": { "zh-CN": "请选择 recall 策略", en: "Choose a recall policy" },
    "用于过滤低相关度 recall 结果。值越高，注入内容越克制。": { "zh-CN": "用于过滤低相关度 recall 结果。值越高，注入内容越克制。", en: "Filters low-relevance recall results. Higher values make injection more conservative." },
    "允许主理人在高相关度时静默注入相关记忆结果。": { "zh-CN": "允许主理人在高相关度时静默注入相关记忆结果。", en: "Allow the lead to silently inject highly relevant memory results." },
    "在 recall 里追加知识图谱的一跳上下文，适合关系型问题。": { "zh-CN": "在 recall 里追加知识图谱的一跳上下文，适合关系型问题。", en: "Append one-hop graph context during recall for relation-heavy questions." },
    "为 recall 增加全文搜索命中，适合精确关键词和文件名。": { "zh-CN": "为 recall 增加全文搜索命中，适合精确关键词和文件名。", en: "Add full-text hits to recall for exact keywords and filenames." },
    "Recall 策略": { "zh-CN": "Recall 策略", en: "Recall policy" },
    "Recall Top-K": { "zh-CN": "Recall Top-K", en: "Recall top-k" },
    "检索阈值": { "zh-CN": "检索阈值", en: "Retrieval threshold" },
    "被动注入 RAG": { "zh-CN": "被动注入 RAG", en: "Passive RAG injection" },
    "图谱扩展": { "zh-CN": "图谱扩展", en: "Graph expansion" },
    "FTS 关键词检索": { "zh-CN": "FTS 关键词检索", en: "FTS keyword search" },
    "偏好加载失败": { "zh-CN": "偏好加载失败", en: "Failed to load preferences" },
    "未能读取 MEMORY.md 中的偏好数据。": { "zh-CN": "未能读取 MEMORY.md 中的偏好数据。", en: "Unable to read preference data from MEMORY.md." },
    "无法保存": { "zh-CN": "无法保存", en: "Unable to save" },
    "偏好的 key 和 value 都不能为空。": { "zh-CN": "偏好的 key 和 value 都不能为空。", en: "Both key and value are required." },
    "偏好已保存": { "zh-CN": "偏好已保存", en: "Preference saved" },
    "删除失败": { "zh-CN": "删除失败", en: "Delete failed" },
    "偏好删除失败，请稍后重试。": { "zh-CN": "偏好删除失败，请稍后重试。", en: "Failed to delete the preference. Please try again." },
    "偏好管理": { "zh-CN": "偏好管理", en: "Preferences" },
    "当前偏好直接回写到 `MEMORY.md`，现在这里可以查看、编辑、增加和删除单条偏好，不再只是只读面板。": { "zh-CN": "当前偏好直接回写到 `MEMORY.md`，现在这里可以查看、编辑、增加和删除单条偏好，不再只是只读面板。", en: "Preferences are written back to MEMORY.md directly. You can view, edit, add, and delete individual entries here." },
    "项目加载失败": { "zh-CN": "项目加载失败", en: "Failed to load projects" },
    "未能读取项目注册表。": { "zh-CN": "未能读取项目注册表。", en: "Unable to load the project registry." },
    "信息不完整": { "zh-CN": "信息不完整", en: "Incomplete data" },
    "项目 ID 和名称不能为空。": { "zh-CN": "项目 ID 和名称不能为空。", en: "Project ID and name are required." },
    "项目已更新": { "zh-CN": "项目已更新", en: "Project updated" },
    "项目已创建": { "zh-CN": "项目已创建", en: "Project created" },
    "项目注册表写入失败，请稍后重试。": { "zh-CN": "项目注册表写入失败，请稍后重试。", en: "Failed to write the project registry. Please try again." },
    "项目已删除": { "zh-CN": "项目已删除", en: "Project deleted" },
    "项目删除失败，请稍后重试。": { "zh-CN": "项目删除失败，请稍后重试。", en: "Failed to delete the project. Please try again." },
    "项目注册表加载中...": { "zh-CN": "项目注册表加载中...", en: "Loading project registry..." },
    "项目注册表": { "zh-CN": "项目注册表", en: "Project registry" },
    "这里可以查看和编辑项目的说明、工作区和默认范围。": { "zh-CN": "这里可以查看和编辑项目的说明、工作区和默认范围。", en: "Inspect and edit project notes, workspaces, and default scopes." },
    "新建项目": { "zh-CN": "新建项目", en: "New project" },
    "刷新": { "zh-CN": "刷新", en: "Refresh" },
    "Artifact Explorer": { "zh-CN": "产物总览", en: "Artifact Explorer" },
    "查看运行中产生的图片、视频、音频、文档和文件挂载记录。": { "zh-CN": "查看运行中产生的图片、视频、音频、文档和文件挂载记录。", en: "Inspect mounted images, videos, audio, documents, and files produced during runtime." },
    "Artifacts": { "zh-CN": "产物", en: "Artifacts" },
    "Artifact Detail": { "zh-CN": "产物详情", en: "Artifact detail" },
    "运行中产生的图片、视频、音频、文档和文件挂载记录。": { "zh-CN": "运行中产生的图片、视频、音频、文档和文件挂载记录。", en: "Mounted records for images, videos, audio, documents, and files generated during runtime." },
    "运行日志": { "zh-CN": "运行日志", en: "Run logs" },
    "查看后台任务、钩子、定时任务和系统动作的详细执行记录。": { "zh-CN": "查看后台任务、钩子、定时任务和系统动作的详细执行记录。", en: "Inspect detailed execution records for background jobs, hooks, cron, and system actions." },
    "自动刷新": { "zh-CN": "自动刷新", en: "Auto refresh" },
    "日志详情": { "zh-CN": "日志详情", en: "Log detail" },
    "执行时间：": { "zh-CN": "执行时间：", en: "Time: " },
    "来源：": { "zh-CN": "来源：", en: "Source: " },
    "动作：": { "zh-CN": "动作：", en: "Action: " },
    "状态：": { "zh-CN": "状态：", en: "Status: " },
    "知识库文档上传": { "zh-CN": "知识库文档上传", en: "Knowledge upload" },
    "支持 PDF, Docx, TXT, Markdown, CSV, Excel, PPTX, HTML 等格式。上传后将自动进行文本解析与基于 Markdown 标题的语义切分，并完成向量化与 FTS 索引，供 Agent 进行 RAG 检索。": { "zh-CN": "支持 PDF, Docx, TXT, Markdown, CSV, Excel, PPTX, HTML 等格式。上传后将自动进行文本解析与基于 Markdown 标题的语义切分，并完成向量化与 FTS 索引，供 Agent 进行 RAG 检索。", en: "Upload PDF, Docx, TXT, Markdown, CSV, Excel, PPTX, HTML, and more. Files are parsed, split semantically by headings when possible, then indexed for vectors and FTS retrieval." },
    "将文件拖拽于此，或": { "zh-CN": "将文件拖拽于此，或", en: "Drop files here, or" },
    "浏览文件": { "zh-CN": "浏览文件", en: "Browse files" },
    "待上传文件": { "zh-CN": "待上传文件", en: "Queued files" },
    "正在处理...": { "zh-CN": "正在处理...", en: "Processing..." },
    "开始上传并解析": { "zh-CN": "开始上传并解析", en: "Upload & parse" },
    "已存在于 RAG 中的文档": { "zh-CN": "已存在于 RAG 中的文档", en: "Indexed documents" },
    "编辑用户": { "zh-CN": "编辑用户", en: "Edit user" },
    "修改用户信息和权限。": { "zh-CN": "修改用户信息和权限。", en: "Update user info and access." },
    "留空表示不修改": { "zh-CN": "留空表示不修改", en: "Leave blank to keep current password" },
    "主理人": { "zh-CN": "主理人", en: "Lead" },
    "这里设置主理人的昵称、头像、默认模型、系统提示词和可用工具。": { "zh-CN": "这里设置主理人的昵称、头像、默认模型、系统提示词和可用工具。", en: "Configure the lead profile, avatar, default model, system prompt, and tool access." },
    "主理人设置": { "zh-CN": "主理人设置", en: "Lead settings" },
    "改这里会影响主理人的显示资料、默认模型和执行方式。": { "zh-CN": "改这里会影响主理人的显示资料、默认模型和执行方式。", en: "Changes here affect the lead profile, default model, and execution mode." },
    "头像地址": { "zh-CN": "头像地址", en: "Avatar URL" },
    "头像上传失败": { "zh-CN": "头像上传失败", en: "Avatar upload failed" },
    "上传中...": { "zh-CN": "上传中...", en: "Uploading..." },
    "上传图片": { "zh-CN": "上传图片", en: "Upload image" },
    "输入 URL": { "zh-CN": "输入 URL", en: "Paste URL" },
    "清空头像": { "zh-CN": "清空头像", en: "Clear avatar" },
    "如：https://...": { "zh-CN": "如：https://...", en: "e.g. https://..." },
    "支持 JPG、PNG、WEBP、GIF，系统会统一处理成 256x256 的静态图片。": { "zh-CN": "支持 JPG、PNG、WEBP、GIF，系统会统一处理成 256x256 的静态图片。", en: "Supports JPG, PNG, WEBP, and GIF. Images are normalized to a 256x256 static avatar." },
    "默认模型": { "zh-CN": "默认模型", en: "Default model" },
    "跟随当前会话使用的模型": { "zh-CN": "跟随当前会话使用的模型", en: "Follow active session model" },
    "输入消息... (Shift + Enter 换行)": { "zh-CN": "输入消息... (Shift + Enter 换行)", en: "Type a message... (Shift+Enter for newline)" },
    "上传文件": { "zh-CN": "上传文件", en: "Upload file" },
    "联网搜索": { "zh-CN": "联网搜索", en: "Web search" },
    "更多选项": { "zh-CN": "更多选项", en: "More" },
    "保存状态": { "zh-CN": "保存状态", en: "Save state" },
    "配置来源": { "zh-CN": "配置来源", en: "Source" },
    "保存后建议重载": { "zh-CN": "保存后建议重载", en: "Reload suggested" },
    "保存后立即生效": { "zh-CN": "保存后立即生效", en: "Live after save" },
    "高级附录": { "zh-CN": "高级附录", en: "Advanced appendix" },
    "这里保留更细的运行规则、能力限制和故障详情，不再承担正式治理首页角色。": { "zh-CN": "这里保留更细的运行规则、能力限制和故障详情，不再承担正式治理首页角色。", en: "Detailed runtime rules, capability limits, and failure details live here. This is no longer the primary governance home." },
    "使用场景": { "zh-CN": "使用场景", en: "Use case" },
    "排障与联调": { "zh-CN": "排障与联调", en: "Debug & tune" },
    "适合查看细项规则和故障详情。": { "zh-CN": "适合查看细项规则和故障详情。", en: "Best for detailed rules and failure details." },
    "主要内容": { "zh-CN": "主要内容", en: "Focus" },
    "细项规则": { "zh-CN": "细项规则", en: "Fine rules" },
    "查看更细的能力策略和限制条件。": { "zh-CN": "查看更细的能力策略和限制条件。", en: "Inspect detailed capability policies and limits." },
    "运行边界": { "zh-CN": "运行边界", en: "Boundary" },
    "Engine 主链": { "zh-CN": "Engine 主链", en: "Engine core path" },
    "所有规则最终都落到 Engine 配置与运行账本。": { "zh-CN": "所有规则最终都落到 Engine 配置与运行账本。", en: "All rules ultimately land in Engine config and runtime ledgers." },
    "故障排查": { "zh-CN": "故障排查", en: "Troubleshooting" },
    "可联动": { "zh-CN": "可联动", en: "Linked" },
    "可和运行与问题页一起定位异常。": { "zh-CN": "可和运行与问题页一起定位异常。", en: "Use it with Ops to pinpoint failures." },
    "安全规则": { "zh-CN": "安全规则", en: "Safety rules" },
    "查看更细的运行规则、能力限制和护栏信息。": { "zh-CN": "查看更细的运行规则、能力限制和护栏信息。", en: "Review fine-grained rules, limits, and guardrails." },
    "运行规则": { "zh-CN": "运行规则", en: "Runtime rules" },
    "查看 Runtime 能力、策略和调度细节。": { "zh-CN": "查看 Runtime 能力、策略和调度细节。", en: "Inspect runtime capabilities, policies, and scheduling details." },
    "故障详情": { "zh-CN": "故障详情", en: "Failure detail" },
    "结合运行与问题页定位异常来源和恢复路径。": { "zh-CN": "结合运行与问题页定位异常来源和恢复路径。", en: "Trace failure sources and recovery paths together with Ops." },
    "AutomationRuntime": { "zh-CN": "AutomationRuntime", en: "AutomationRuntime" },
    "AutomationRuntime 是核心主链，负责 Hooks、Cron 与系统自动化触发。": { "zh-CN": "AutomationRuntime 是核心主链，负责 Hooks、Cron 与系统自动化触发。", en: "AutomationRuntime is the core path for hooks, cron jobs, and system automations." },
    "核心 Runtime": { "zh-CN": "核心 Runtime", en: "Core runtime" },
    "不可关闭": { "zh-CN": "不可关闭", en: "Always on" },
    "动作钩子": { "zh-CN": "动作钩子", en: "Hooks" },
    "管理生命周期钩子、触发动作和系统自动化入口。": { "zh-CN": "管理生命周期钩子、触发动作和系统自动化入口。", en: "Manage lifecycle hooks, trigger actions, and automation entry points." },
    "定时任务": { "zh-CN": "定时任务", en: "Cron" },
    "管理 Cron、计划任务和周期性执行。": { "zh-CN": "管理 Cron、计划任务和周期性执行。", en: "Manage cron jobs, schedules, and recurring runs." },
    "进入 动作钩子": { "zh-CN": "进入 动作钩子", en: "Open Hooks" },
    "进入 定时任务": { "zh-CN": "进入 定时任务", en: "Open Cron" },
    "上下文配置": { "zh-CN": "上下文配置", en: "Context config" },
    "基础预算与边界": { "zh-CN": "基础预算与边界", en: "Budgets & limits" },
    "这里决定何时开始压缩旧上下文，以及整体会话的反思上限。": { "zh-CN": "这里决定何时开始压缩旧上下文，以及整体会话的反思上限。", en: "Define when to compress old context and how much reflection budget to keep." },
    "摘要策略": { "zh-CN": "摘要策略", en: "Summary policy" },
    "这里决定系统优先保留什么，以及何时才值得调用摘要模型。": { "zh-CN": "这里决定系统优先保留什么，以及何时才值得调用摘要模型。", en: "Decide what to preserve first and when summarization is worth the cost." },
    "Channel 适配": { "zh-CN": "Channel 适配", en: "Channel adaptation" },
    "群聊和渠道消息保留 speaker-aware 窗口，但不再拥有独立的压缩判定权。": { "zh-CN": "群聊和渠道消息保留 speaker-aware 窗口，但不再拥有独立的压缩判定权。", en: "Group and channel messages keep speaker-aware windows but no longer own independent compression rules." },
    "Automation 适配": { "zh-CN": "Automation 适配", en: "Automation adaptation" },
    "自动化会继续保留 recent runs 和 job memory，但通过统一上下文治理主链进入 prompt。": { "zh-CN": "自动化会继续保留 recent runs 和 job memory，但通过统一上下文治理主链进入 prompt。", en: "Automation keeps recent runs and job memory, but enters prompts through the unified context path." },
    "候选重排": { "zh-CN": "候选重排", en: "Rerank" },
    "已安装的 Skills": { "zh-CN": "已安装的 Skills", en: "Installed skills" },
    "这里显示系统当前能读取的 Skills 目录和说明。": { "zh-CN": "这里显示系统当前能读取的 Skills 目录和说明。", en: "See the skills currently readable by the system." },
    "还没有可用 Skills": { "zh-CN": "还没有可用 Skills", en: "No skills yet" },
    "你可以通过命令行安装或上传压缩包添加新的 Skills。": { "zh-CN": "你可以通过命令行安装或上传压缩包添加新的 Skills。", en: "Install skills from CLI or upload a bundle to add more." },
    "MCP 服务": { "zh-CN": "MCP 服务", en: "MCP servers" },
    "这里显示当前已登记的 MCP 服务、连通状态和工具数量。": { "zh-CN": "这里显示当前已登记的 MCP 服务、连通状态和工具数量。", en: "Inspect registered MCP servers, connectivity, and tool counts." },
    "还没有 MCP 服务": { "zh-CN": "还没有 MCP 服务", en: "No MCP servers" },
    "你可以导入一份 MCP JSON 配置，把新的 MCP 服务接到系统里。": { "zh-CN": "你可以导入一份 MCP JSON 配置，把新的 MCP 服务接到系统里。", en: "Import an MCP JSON config to connect new services." },
    "添加 Skills": { "zh-CN": "添加 Skills", en: "Add skills" },
    "你可以通过受支持的命令或压缩包把新的 Skills 加入系统。": { "zh-CN": "你可以通过受支持的命令或压缩包把新的 Skills 加入系统。", en: "Add new skills through supported commands or bundles." },
    "MCP 配置": { "zh-CN": "MCP 配置", en: "MCP config" },
    "把 MCP JSON 配置贴进来后，系统会自动合并并刷新服务。": { "zh-CN": "把 MCP JSON 配置贴进来后，系统会自动合并并刷新服务。", en: "Paste MCP JSON here and the system will merge and reload it." },
    "最近使用摘要": { "zh-CN": "最近使用摘要", en: "Recent usage" },
    "这里显示最近窗口内的 Skills 和 MCP 使用情况。": { "zh-CN": "这里显示最近窗口内的 Skills 和 MCP 使用情况。", en: "Recent skill and MCP usage appears here." },
    "还没有最近使用摘要": { "zh-CN": "还没有最近使用摘要", en: "No recent usage" },
    "等扩展实际参与一次运行后，这里会显示最近命中情况。": { "zh-CN": "等扩展实际参与一次运行后，这里会显示最近命中情况。", en: "Usage will appear after extensions participate in a run." },
    "当前候选暴露": { "zh-CN": "当前候选暴露", en: "Current exposure" },
    "这里显示最近窗口内暴露给主理人的 Skills 与 MCP 候选规模。": { "zh-CN": "这里显示最近窗口内暴露给主理人的 Skills 与 MCP 候选规模。", en: "See how many skill and MCP candidates are currently exposed to the lead." },
    "还没有候选暴露摘要": { "zh-CN": "还没有候选暴露摘要", en: "No exposure snapshot" },
    "等扩展参与一次实际运行后，这里会显示最近暴露规模。": { "zh-CN": "等扩展参与一次实际运行后，这里会显示最近暴露规模。", en: "Exposure stats will appear after a real run." },
    "主工作区": { "zh-CN": "主工作区", en: "Primary workspace" },
    "用户管理": { "zh-CN": "用户管理", en: "User management" },
    "新建用户": { "zh-CN": "新建用户", en: "New user" },
    "用户列表": { "zh-CN": "用户列表", en: "User list" },
    "登录名": { "zh-CN": "登录名", en: "Login" },
    "昵称": { "zh-CN": "昵称", en: "Name" },
    "初始密码": { "zh-CN": "初始密码", en: "Initial password" },
    "角色": { "zh-CN": "角色", en: "Role" },
    "普通用户": { "zh-CN": "普通用户", en: "User" },
    "管理员": { "zh-CN": "管理员", en: "Admin" },
    "下次登录要求改密": { "zh-CN": "下次登录要求改密", en: "Force reset on next sign-in" },
    "创建用户": { "zh-CN": "创建用户", en: "Create user" },
    "改密": { "zh-CN": "改密", en: "Pwd reset" },
    "操作": { "zh-CN": "操作", en: "Actions" },
    "需要": { "zh-CN": "需要", en: "Required" },
    "无需": { "zh-CN": "无需", en: "No" },
    "删除": { "zh-CN": "删除", en: "Delete" },
    "重置密码": { "zh-CN": "重置密码", en: "Reset password" },
    "保存修改": { "zh-CN": "保存修改", en: "Save changes" },
    "例如：admin": { "zh-CN": "例如：admin", en: "Example: admin" },
    "例如：管理员": { "zh-CN": "例如：管理员", en: "Example: Admin" },
    "至少 6 位": { "zh-CN": "至少 6 位", en: "At least 6 characters" },
    "身份标签": { "zh-CN": "身份标签", en: "Role label" },
    "头像": { "zh-CN": "头像", en: "Avatar" },
    "如：智能主管": { "zh-CN": "如：智能主管", en: "e.g. Lead Ops" },
    "如：主理人": { "zh-CN": "如：主理人", en: "e.g. Lead" },
    "连接成功": { "zh-CN": "连接成功", en: "Connected" },
    "连接异常": { "zh-CN": "连接异常", en: "Connection issue" },
    "连接失败": { "zh-CN": "连接失败", en: "Connection failed" },
    "保存失败": { "zh-CN": "保存失败", en: "Save failed" },
    "请稍后重试": { "zh-CN": "请稍后重试", en: "Please try again later." },
    "主理人设置已保存": { "zh-CN": "主理人设置已保存", en: "Lead settings saved" },
    "新的昵称、头像和工具权限已经生效。": { "zh-CN": "新的昵称、头像和工具权限已经生效。", en: "The updated profile, avatar, and tool permissions are live." },
    "记忆管理": { "zh-CN": "记忆管理", en: "Memory" },
    "分层记忆系统 • 偏好画像 • 项目注册表 • 知识库 • Artifact Explorer • 知识图谱": { "zh-CN": "分层记忆系统 • 偏好画像 • 项目注册表 • 知识库 • Artifact Explorer • 知识图谱", en: "Layered memory • Preferences • Project registry • Knowledge • Artifact explorer • Graph" },
    "偏好项": { "zh-CN": "偏好项", en: "Preferences" },
    "项目上下文": { "zh-CN": "项目上下文", en: "Project context" },
    "知识条目": { "zh-CN": "知识条目", en: "Knowledge items" },
    "图谱实体": { "zh-CN": "图谱实体", en: "Graph entities" },
    "仪表盘加载失败": { "zh-CN": "仪表盘加载失败", en: "Dashboard load failed" },
    "未能读取记忆系统仪表盘。": { "zh-CN": "未能读取记忆系统仪表盘。", en: "Unable to load the memory dashboard." },
    "知识库加载失败": { "zh-CN": "知识库加载失败", en: "Knowledge load failed" },
    "未能读取知识条目。": { "zh-CN": "未能读取知识条目。", en: "Unable to load knowledge items." },
    "确定要删除这条知识吗？(同时会删除 FTS5 索引)": { "zh-CN": "确定要删除这条知识吗？(同时会删除 FTS5 索引)", en: "Delete this knowledge item? The FTS5 index will be removed too." },
    "知识条目删除失败，请稍后重试。": { "zh-CN": "知识条目删除失败，请稍后重试。", en: "Failed to delete the knowledge item. Please try again." },
    "知识已更新": { "zh-CN": "知识已更新", en: "Knowledge updated" },
    "批量删除完成": { "zh-CN": "批量删除完成", en: "Bulk delete complete" },
    "选中的知识条目已从记忆库移除。": { "zh-CN": "选中的知识条目已从记忆库移除。", en: "Selected knowledge items were removed from memory." },
    "检索失败": { "zh-CN": "检索失败", en: "Search failed" },
    "当前无法搜索知识库，请稍后重试。": { "zh-CN": "当前无法搜索知识库，请稍后重试。", en: "The knowledge base is unavailable right now. Please try again later." },
    "未能读取当前运行中的多模态产物。": { "zh-CN": "未能读取当前运行中的多模态产物。", en: "Unable to load runtime artifacts." },
    "Artifact 详情加载失败": { "zh-CN": "Artifact 详情加载失败", en: "Artifact detail failed" },
    "当前先展示已缓存信息，你可以稍后重试。": { "zh-CN": "当前先展示已缓存信息，你可以稍后重试。", en: "Showing cached artifact info for now. Try again later." },
    "暂无路径信息": { "zh-CN": "暂无路径信息", en: "No path info yet" },
    "未知时间": { "zh-CN": "未知时间", en: "Unknown time" },
    "创建时间": { "zh-CN": "创建时间", en: "Created at" },
    "图片与截图": { "zh-CN": "图片与截图", en: "Images" },
    "视频与录屏": { "zh-CN": "视频与录屏", en: "Videos" },
    "音频与语音": { "zh-CN": "音频与语音", en: "Audio" },
    "文档与结构化材料": { "zh-CN": "文档与结构化材料", en: "Documents" },
    "其它二进制文件": { "zh-CN": "其它二进制文件", en: "Files" },
    "统一挂载层总量": { "zh-CN": "统一挂载层总量", en: "Mounted total" },
    "搜索标题、artifactId、sessionId、路径...": { "zh-CN": "搜索标题、artifactId、sessionId、路径...", en: "Search title, artifactId, sessionId, path..." },
    "筛选类型": { "zh-CN": "筛选类型", en: "Type" },
    "全部类型": { "zh-CN": "全部类型", en: "All types" },
    "图片": { "zh-CN": "图片", en: "Images" },
    "视频": { "zh-CN": "视频", en: "Videos" },
    "音频": { "zh-CN": "音频", en: "Audio" },
    "文档": { "zh-CN": "文档", en: "Docs" },
    "文件": { "zh-CN": "文件", en: "Files" },
    "Artifact Explorer 加载中...": { "zh-CN": "Artifact Explorer 加载中...", en: "Loading Artifact Explorer..." },
    "当前没有命中的 artifact。等图片/视频/文档进入运行链后，这里会自动出现。": { "zh-CN": "当前没有命中的 artifact。等图片/视频/文档进入运行链后，这里会自动出现。", en: "No artifacts yet. Items will appear here once images, videos, or documents enter the runtime." },
    "查看当前选中 artifact 的完整路径、元数据和预览。": { "zh-CN": "查看当前选中 artifact 的完整路径、元数据和预览。", en: "Inspect the selected artifact path, metadata, and preview." },
    "点击左侧卡片查看详情。": { "zh-CN": "点击左侧卡片查看详情。", en: "Select an artifact card to inspect it." },
    "暂无预览链接": { "zh-CN": "暂无预览链接", en: "No preview link" },
    "触发来源": { "zh-CN": "触发来源", en: "Source" },
    "全部来源 (All)": { "zh-CN": "全部来源 (All)", en: "All sources" },
    "系统动作": { "zh-CN": "系统动作", en: "System" },
    "执行状态": { "zh-CN": "执行状态", en: "Status" },
    "全部状态 (All)": { "zh-CN": "全部状态 (All)", en: "All statuses" },
    "成功": { "zh-CN": "成功", en: "Success" },
    "失败": { "zh-CN": "失败", en: "Failed" },
    "跳过": { "zh-CN": "跳过", en: "Skipped" },
    "执行时间": { "zh-CN": "执行时间", en: "Time" },
    "来源": { "zh-CN": "来源", en: "Source" },
    "执行动作": { "zh-CN": "执行动作", en: "Action" },
    "详情": { "zh-CN": "详情", en: "Details" },
    "暂无日志记录": { "zh-CN": "暂无日志记录", en: "No logs yet" },
    "查看详情": { "zh-CN": "查看详情", en: "View" },
    "加载更多记录": { "zh-CN": "加载更多记录", en: "Load more" },
    "推荐单个文件大小不要超过 20MB。系统自动过滤不受支持的扩展名。": { "zh-CN": "推荐单个文件大小不要超过 20MB。系统自动过滤不受支持的扩展名。", en: "Keep individual files under 20MB when possible. Unsupported extensions are filtered automatically." },
    "语义块大小 (Chunk Size)": { "zh-CN": "语义块大小 (Chunk Size)", en: "Chunk size" },
    "影响最大检索分块长度。文档将优先按标题进行语义切分。": { "zh-CN": "影响最大检索分块长度。文档将优先按标题进行语义切分。", en: "Controls the max retrieval chunk length. Documents prefer heading-aware splitting first." },
    "分块重叠度 (Chunk Overlap)": { "zh-CN": "分块重叠度 (Chunk Overlap)", en: "Chunk overlap" },
    "当退化为固定字数切块时，相邻块之间的字符重叠量。": { "zh-CN": "当退化为固定字数切块时，相邻块之间的字符重叠量。", en: "Character overlap between adjacent chunks when fallback fixed-size splitting is used." },
    "所有文件处理完毕后，您可以直接在「知识库」或「Agent 助手」中测试检索效果。": { "zh-CN": "所有文件处理完毕后，您可以直接在「知识库」或「Agent 助手」中测试检索效果。", en: "After processing, test retrieval directly from Knowledge or the Agent Assistant." },
    "卸载该文档": { "zh-CN": "卸载该文档", en: "Remove document" },
    "未知供应商": { "zh-CN": "未知供应商", en: "Unknown provider" },
    "系统提示词": { "zh-CN": "系统提示词", en: "System prompt" },
    "这里决定主理人如何理解任务、组织步骤和调用能力。": { "zh-CN": "这里决定主理人如何理解任务、组织步骤和调用能力。", en: "This defines how the lead interprets tasks, plans steps, and uses capabilities." },
    "请描述主理人的职责、做事风格和能力边界。": { "zh-CN": "请描述主理人的职责、做事风格和能力边界。", en: "Describe the lead's role, working style, and capability boundaries." },
    "工具权限概览": { "zh-CN": "工具权限概览", en: "Tool access overview" },
    "这里会显示主理人当前能直接使用的工具范围，避免误开高风险底层能力。": { "zh-CN": "这里会显示主理人当前能直接使用的工具范围，避免误开高风险底层能力。", en: "See which tools the lead can use directly and avoid opening risky low-level capabilities by mistake." },
    "系统固定能力": { "zh-CN": "系统固定能力", en: "Core capabilities" },
    "由系统统一调度的核心能力": { "zh-CN": "由系统统一调度的核心能力", en: "Core capabilities managed by the system." },
    "这部分能力由主理人与各 runtime 主链自动获得，不在这里单独勾选或修改。": { "zh-CN": "这部分能力由主理人与各 runtime 主链自动获得，不在这里单独勾选或修改。", en: "These capabilities are granted automatically by the lead and runtime core paths. They are not configured here." },
    "系统默认工具": { "zh-CN": "系统默认工具", en: "System tools" },
    "这些工具由系统统一提供，主理人始终可用。": { "zh-CN": "这些工具由系统统一提供，主理人始终可用。", en: "These tools are provided by the system and always available to the lead." },
    "当前没有额外的运行时默认能力分组": { "zh-CN": "当前没有额外的运行时默认能力分组", en: "No extra runtime-managed capability groups." },
    "这部分能力由各 runtime 统一调度，不在这里单独勾选。": { "zh-CN": "这部分能力由各 runtime 统一调度，不在这里单独勾选。", en: "These capabilities are managed by runtimes and are not configured here." },
    "主理人的职责": { "zh-CN": "主理人的职责", en: "Lead scope" },
    "主理人会负责理解任务、安排步骤，并在需要时调用桌面操作、自动化运行时任务、插件宿主渠道能力和其他专项能力。这里主要决定它的显示资料、默认模型和可直接使用的工具。": { "zh-CN": "主理人会负责理解任务、安排步骤，并在需要时调用桌面操作、自动化运行时任务、插件宿主渠道能力和其他专项能力。这里主要决定它的显示资料、默认模型和可直接使用的工具。", en: "The lead interprets tasks, plans steps, and can call desktop actions, automation runtimes, plugin-host channel capabilities, and other specialized abilities. This page controls its profile, default model, and directly available tools." },
    "系统默认可用的工具": { "zh-CN": "系统默认可用的工具", en: "Default system tools" },
    "这些工具由系统统一提供，主理人默认可用，这里只做展示。": { "zh-CN": "这些工具由系统统一提供，主理人默认可用，这里只做展示。", en: "These tools are provided by the system and available by default. They are shown here for reference only." },
    "暂无说明。": { "zh-CN": "暂无说明。", en: "No description." },
    "当前没有默认展示的系统工具。": { "zh-CN": "当前没有默认展示的系统工具。", en: "No default system tools are shown right now." },
    "由 runtime 主链统一管理。": { "zh-CN": "由 runtime 主链统一管理。", en: "Managed by the runtime core path." },
    "当前没有额外的 runtime 默认能力。": { "zh-CN": "当前没有额外的 runtime 默认能力。", en: "No extra runtime-managed capabilities." },
    "外部 / MCP 补充工具": { "zh-CN": "外部 / MCP 补充工具", en: "External / MCP tools" },
    "这里只配置主理人可直接使用的补充 MCP 工具。系统原生工具和 runtime 默认能力不会在这里单独保存。": { "zh-CN": "这里只配置主理人可直接使用的补充 MCP 工具。系统原生工具和 runtime 默认能力不会在这里单独保存。", en: "Configure only the extra MCP tools the lead can use directly. Native system tools and runtime defaults are not stored here." },
    "当前没有可单独配置的 MCP 补充工具。": { "zh-CN": "当前没有可单独配置的 MCP 补充工具。", en: "No configurable MCP tools are available right now." },
    "保存配置": { "zh-CN": "保存配置", en: "Save config" },
    "测试连接": { "zh-CN": "测试连接", en: "Test" },
    "工具": { "zh-CN": "工具", en: "tools" },
    "已全选": { "zh-CN": "已全选", en: "All selected" },
    "通用工具": { "zh-CN": "通用工具", en: "General tools" },
    "已成功连接到 MCP 服务器": { "zh-CN": "已成功连接到 MCP 服务器", en: "Connected to MCP server" },
    "未能从服务器获取到工具列表，请检查配置。": { "zh-CN": "未能从服务器获取到工具列表，请检查配置。", en: "The server returned no tools. Check the configuration." },
    "测试连接出错": { "zh-CN": "测试连接出错", en: "Connection test failed" },
    "子智能体": { "zh-CN": "子智能体", en: "Subagents" },
    "管理隶属于主理人的子智能体目录、职责、模型和工具权限。": { "zh-CN": "管理隶属于主理人的子智能体目录、职责、模型和工具权限。", en: "Manage the lead's subagent roster, roles, models, and tool access." },
    "新建子智能体": { "zh-CN": "新建子智能体", en: "New subagent" },
    "暂无描述": { "zh-CN": "暂无描述", en: "No description yet" },
    "主理人创建": { "zh-CN": "主理人创建", en: "Created by lead" },
    "暂无子智能体。点击“新建子智能体”开始补充主理人的协作助手。": { "zh-CN": "暂无子智能体。点击“新建子智能体”开始补充主理人的协作助手。", en: "No subagents yet. Create one to add more collaborators for the lead." },
    "编辑子智能体": { "zh-CN": "编辑子智能体", en: "Edit subagent" },
    "子智能体名称": { "zh-CN": "子智能体名称", en: "Subagent name" },
    "例如：代码助手": { "zh-CN": "例如：代码助手", en: "e.g. Coding assistant" },
    "角色标签 (可选)": { "zh-CN": "角色标签 (可选)", en: "Role label (optional)" },
    "例如：专家": { "zh-CN": "例如：专家", en: "e.g. Specialist" },
    "图标 (Emoji)": { "zh-CN": "图标 (Emoji)", en: "Icon (emoji)" },
    "已启用头像，此项仅作为备用": { "zh-CN": "已启用头像，此项仅作为备用", en: "Avatar enabled. This icon is a fallback." },
    "职责说明": { "zh-CN": "职责说明", en: "Role summary" },
    "简要说明这个子智能体负责什么...": { "zh-CN": "简要说明这个子智能体负责什么...", en: "Briefly describe what this subagent handles..." },
    "选择模型": { "zh-CN": "选择模型", en: "Choose model" },
    "使用前请先在模型中心完成模型配置。": { "zh-CN": "使用前请先在模型中心完成模型配置。", en: "Configure the model in Model Hub before using it here." },
    "工具权限": { "zh-CN": "工具权限", en: "Tool access" },
    "暂无可用 MCP 工具，请前往 MCP 面板配置。": { "zh-CN": "暂无可用 MCP 工具，请前往 MCP 面板配置。", en: "No MCP tools are available. Configure them from the MCP page." },
    "你是一个...": { "zh-CN": "你是一个...", en: "You are a..." },
    "定义 AI 的角色、行为和限制。": { "zh-CN": "定义 AI 的角色、行为和限制。", en: "Define the AI role, behavior, and limits." },
    "开启自我检查": { "zh-CN": "开启自我检查", en: "Enable self-check" },
    "最大反思次数 (Max Reflections)": { "zh-CN": "最大反思次数 (Max Reflections)", en: "Max reflections" },
    "当工具执行错误或效果不佳时，子智能体会自动补一次检查并尝试修复。": { "zh-CN": "当工具执行错误或效果不佳时，子智能体会自动补一次检查并尝试修复。", en: "If tool execution fails or performs poorly, the subagent adds one self-check pass and tries to recover." },
    "保存子智能体": { "zh-CN": "保存子智能体", en: "Save subagent" },
    "系统基础配置": { "zh-CN": "系统基础配置", en: "System base" },
    "这里管理服务地址、内部密钥、抓取缓存和桌面依赖。": { "zh-CN": "这里管理服务地址、内部密钥、抓取缓存和桌面依赖。", en: "Manage service addresses, internal secrets, fetch cache, and desktop dependencies here." },
    "引擎地址": { "zh-CN": "引擎地址", en: "Engine URL" },
    "影响管理台和网页端连接引擎的地址。": { "zh-CN": "影响管理台和网页端连接引擎的地址。", en: "Affects how Admin and Web connect to Engine." },
    "管理台地址": { "zh-CN": "管理台地址", en: "Admin URL" },
    "影响网页端连接管理台接口的地址。": { "zh-CN": "影响网页端连接管理台接口的地址。", en: "Affects how Web connects to Admin APIs." },
    "桌面依赖": { "zh-CN": "桌面依赖", en: "Desktop stack" },
    "影响 OCR 和桌面自动化能力。": { "zh-CN": "影响 OCR 和桌面自动化能力。", en: "Affects OCR and desktop automation." },
    "浏览器来源": { "zh-CN": "浏览器来源", en: "Browser origins" },
    "控制远端网页、局域网地址和反向代理域名的跨域访问。": { "zh-CN": "控制远端网页、局域网地址和反向代理域名的跨域访问。", en: "Controls browser access from remote web, LAN addresses, and reverse-proxy domains." },
    "未设置": { "zh-CN": "未设置", en: "Unset" },
    "已就绪": { "zh-CN": "已就绪", en: "Ready" },
    "部分可用": { "zh-CN": "部分可用", en: "Partial" },
    "需要补充": { "zh-CN": "需要补充", en: "Needs setup" },
    "仅本机默认地址": { "zh-CN": "仅本机默认地址", en: "Local defaults only" },
    "流畅": { "zh-CN": "流畅", en: "Smooth" },
    "更省资源，适合手机和局域网观察。": { "zh-CN": "更省资源，适合手机和局域网观察。", en: "Uses fewer resources. Good for phones and LAN viewing." },
    "平衡": { "zh-CN": "平衡", en: "Balanced" },
    "默认推荐，清晰度和流畅度比较均衡。": { "zh-CN": "默认推荐，清晰度和流畅度比较均衡。", en: "Recommended default. Balanced clarity and smoothness." },
    "清晰": { "zh-CN": "清晰", en: "Clear" },
    "画面更清楚，但更占用服务端和网络资源。": { "zh-CN": "画面更清楚，但更占用服务端和网络资源。", en: "Sharper output, but uses more server and network resources." },
    "必须装": { "zh-CN": "必须装", en: "Required" },
    "用到再装": { "zh-CN": "用到再装", en: "Install when needed" },
    "增强可选": { "zh-CN": "增强可选", en: "Optional boost" },
    "服务联通": { "zh-CN": "服务联通", en: "Connectivity" },
    "改这里会影响管理台、网页端和引擎之间的连接。": { "zh-CN": "改这里会影响管理台、网页端和引擎之间的连接。", en: "Changes here affect connectivity between Admin, Web, and Engine." },
    "引擎 HTTP 地址": { "zh-CN": "引擎 HTTP 地址", en: "Engine HTTP URL" },
    "引擎 WS 地址": { "zh-CN": "引擎 WS 地址", en: "Engine WS URL" },
    "管理台 API 地址": { "zh-CN": "管理台 API 地址", en: "Admin API URL" },
    "内部密钥": { "zh-CN": "内部密钥", en: "Internal secret" },
    "自动生成": { "zh-CN": "自动生成", en: "Auto-generate" },
    "允许的浏览器来源": { "zh-CN": "允许的浏览器来源", en: "Allowed browser origins" },
    "每行填写一个来源地址。这里用于远端网页、局域网访问和反向代理域名，不影响引擎内部运行，只影响浏览器跨域访问。修改后需要重启 Engine 才会更新实际 CORS allowlist。": { "zh-CN": "每行填写一个来源地址。这里用于远端网页、局域网访问和反向代理域名，不影响引擎内部运行，只影响浏览器跨域访问。修改后需要重启 Engine 才会更新实际 CORS allowlist。", en: "Enter one origin per line. This controls browser CORS access for remote web, LAN, and reverse-proxy domains. Engine must restart before the live CORS allowlist updates." },
    "抓取与缓存": { "zh-CN": "抓取与缓存", en: "Fetch & cache" },
    "改这里会影响网页抓取、代理绕过和缓存文件位置。": { "zh-CN": "改这里会影响网页抓取、代理绕过和缓存文件位置。", en: "Changes here affect web fetch, proxy bypassing, and cache file locations." },
    "绕过代理环境变量": { "zh-CN": "绕过代理环境变量", en: "Bypass proxy env" },
    "打开后会忽略异常代理变量，直接访问网页。": { "zh-CN": "打开后会忽略异常代理变量，直接访问网页。", en: "Ignore broken proxy environment variables and fetch pages directly." },
    "缓存目录": { "zh-CN": "缓存目录", en: "Cache directory" },
    "自适应存储文件": { "zh-CN": "自适应存储文件", en: "Adaptive storage file" },
    "块": { "zh-CN": "块", en: "chunks" },
    "确定要卸载文档": { "zh-CN": "确定要卸载文档", en: "Remove document" },
    "及其": { "zh-CN": "及其", en: "and its" },
    "个语义切块吗？(将从知识库和向量库中彻底删除)": { "zh-CN": "个语义切块吗？(将从知识库和向量库中彻底删除)", en: "semantic chunks? This removes it from both knowledge and vector stores." },
    "卸载失败": { "zh-CN": "卸载失败", en: "Remove failed" },
    "卸载出错": { "zh-CN": "卸载出错", en: "Remove request failed" },
    "还没有项目。先创建一个项目，方便会话和自动任务复用同一套项目范围。": { "zh-CN": "还没有项目。先创建一个项目，方便会话和自动任务复用同一套项目范围。", en: "No projects yet. Create one so sessions and automations can share the same scope." },
    "默认": { "zh-CN": "默认", en: "Default" },
    "暂无描述，点击后可查看全文并编辑。": { "zh-CN": "暂无描述，点击后可查看全文并编辑。", en: "No description yet. Open it to view and edit the full text." },
    "查看 / 编辑项目": { "zh-CN": "查看 / 编辑项目", en: "View / edit project" },
    "创建项目": { "zh-CN": "创建项目", en: "Create project" },
    "这里可以集中查看和修改项目说明、工作区目录和默认范围。": { "zh-CN": "这里可以集中查看和修改项目说明、工作区目录和默认范围。", en: "Review and edit project notes, workspace paths, and default scope here." },
    "原始记录": { "zh-CN": "原始记录", en: "Raw record" },
    "项目 ID": { "zh-CN": "项目 ID", en: "Project ID" },
    "例如 v8-agent-os": { "zh-CN": "例如 v8-agent-os", en: "e.g. v8-agent-os" },
    "项目名称": { "zh-CN": "项目名称", en: "Project name" },
    "例如 V8 Agent OS 主工程": { "zh-CN": "例如 V8 Agent OS 主工程", en: "e.g. V8 Agent OS main workspace" },
    "描述全文": { "zh-CN": "描述全文", en: "Full description" },
    "写清楚这个项目是做什么的，以及需要长期记住的约束。": { "zh-CN": "写清楚这个项目是做什么的，以及需要长期记住的约束。", en: "Describe what the project does and which long-term constraints should be remembered." },
    "工作区标识": { "zh-CN": "工作区标识", en: "Workspace ID" },
    "例如 main-workspace": { "zh-CN": "例如 main-workspace", en: "e.g. main-workspace" },
    "工作区目录": { "zh-CN": "工作区目录", en: "Workspace path" },
    "例如 E:\\Projects\\V8-Agent-OS": { "zh-CN": "例如 E:\\Projects\\V8-Agent-OS", en: "e.g. E:\\Projects\\V8-Agent-OS" },
    "默认范围": { "zh-CN": "默认范围", en: "Default scope" },
    "例如 project:v8-agent-os": { "zh-CN": "例如 project:v8-agent-os", en: "e.g. project:v8-agent-os" },
    "例如 memory, rag, realtime": { "zh-CN": "例如 memory, rag, realtime", en: "e.g. memory, rag, realtime" },
    "Tags": { "zh-CN": "Tags", en: "Tags" },
    "保存": { "zh-CN": "保存", en: "Save" },
    "已开启": { "zh-CN": "已开启", en: "Enabled" },
    "已关闭": { "zh-CN": "已关闭", en: "Disabled" },
    "禁止持久化回退": { "zh-CN": "禁止持久化回退", en: "Block durability fallback" },
    "关闭后长期任务更容易丢失运行状态。": { "zh-CN": "关闭后长期任务更容易丢失运行状态。", en: "Turning this off makes long-running tasks more likely to lose state." },
    "选择一个 AI 模型": { "zh-CN": "选择一个 AI 模型", en: "Select a model" },
    "子智能体更新成功！": { "zh-CN": "子智能体更新成功！", en: "Subagent updated." },
    "子智能体创建成功！": { "zh-CN": "子智能体创建成功！", en: "Subagent created." },
    "未知错误": { "zh-CN": "未知错误", en: "Unknown error" },
    "保存失败，请检查网络连接": { "zh-CN": "保存失败，请检查网络连接", en: "Save failed. Check your network connection." },
    "确定要删除这个子智能体吗？": { "zh-CN": "确定要删除这个子智能体吗？", en: "Delete this subagent?" },
    "未知模型": { "zh-CN": "未知模型", en: "Unknown model" },
    "上传失败": { "zh-CN": "上传失败", en: "Upload failed" },
    "上传出错": { "zh-CN": "上传出错", en: "Upload request failed" },
    "知识图谱": { "zh-CN": "知识图谱", en: "Graph" },
    "记忆助手": { "zh-CN": "记忆助手", en: "Memory agent" },
    "系统日志": { "zh-CN": "系统日志", en: "Logs" },
    "文档上传": { "zh-CN": "文档上传", en: "Upload" },
    "配置": { "zh-CN": "配置", en: "Config" },
    "搜索知识... 支持中英文": { "zh-CN": "搜索知识... 支持中英文", en: "Search knowledge... Chinese & English" },
    "FTS5 + jieba 已索引": { "zh-CN": "FTS5 + jieba 已索引", en: "Indexed with FTS5 + jieba" },
    "偏好写入失败，请稍后重试。": { "zh-CN": "偏好写入失败，请稍后重试。", en: "Failed to write the preference. Please try again." },
    "偏好已删除": { "zh-CN": "偏好已删除", en: "Preference deleted" },
    "新 scope，例如 project:v8-agent-os": { "zh-CN": "新 scope，例如 project:v8-agent-os", en: "New scope, e.g. project:v8-agent-os" },
    "新增 scope": { "zh-CN": "新增 scope", en: "Add scope" },
    "偏好加载中...": { "zh-CN": "偏好加载中...", en: "Loading preferences..." },
    "还没有可编辑的偏好项，可以先新增一个 scope，再添加条目。": { "zh-CN": "还没有可编辑的偏好项，可以先新增一个 scope，再添加条目。", en: "No editable preferences yet. Add a scope first, then create entries." },
    "添加偏好": { "zh-CN": "添加偏好", en: "Add preference" },
    "这个 scope 还没有偏好，点击上方按钮添加一条即可。": { "zh-CN": "这个 scope 还没有偏好，点击上方按钮添加一条即可。", en: "This scope has no preferences yet. Use the button above to add one." },
    "偏好内容": { "zh-CN": "偏好内容", en: "Preference value" },
    "会话后自动提取": { "zh-CN": "会话后自动提取", en: "Extract after session" },
    "控制 Memory Agent 是否在会话完成后自动提取偏好和知识。": { "zh-CN": "控制 Memory Agent 是否在会话完成后自动提取偏好和知识。", en: "Control whether Memory Agent extracts preferences and knowledge after a session ends." },
    "上下文窗口": { "zh-CN": "上下文窗口", en: "Context window" },
    "控制近期日志与记忆注入窗口，让 recall 与长期记忆注入保持节奏一致。": { "zh-CN": "控制近期日志与记忆注入窗口，让 recall 与长期记忆注入保持节奏一致。", en: "Tune recent-log and memory-injection windows so recall stays aligned with long-term memory injection." },
    "近期日志天数": { "zh-CN": "近期日志天数", en: "Recent log days" },
    "最大上下文 Token": { "zh-CN": "最大上下文 Token", en: "Max context tokens" },
    "全局偏好": { "zh-CN": "全局偏好", en: "Global preferences" },
    "Quick commands": { "zh-CN": "快捷指令", en: "Quick commands" },
    "输入指令... 如「记住我喜欢 dark mode」": { "zh-CN": "输入指令... 如「记住我喜欢 dark mode」", en: "Enter a request... e.g. remember I like dark mode" },
};

export function localizeAdminText(locale: Locale, value: LocalizedText | string): string {
    if (typeof value !== "string") {
        return pickLocalizedText(locale, value);
    }
    const mapped = ADMIN_TEXT_MAP[value];
    return mapped ? pickLocalizedText(locale, mapped) : value;
}
