export const BASELINE_SYSTEM_TOOLS = [
    "ask_user",
    "read_native_file",
    "write_native_file",
    "grep_search",
    "run_system_command",
    "read_background_output",
    "send_background_input",
    "terminate_background_command",
    "download_media_for_vision",
    "vision_media_analyzer",
    "web_fetch",
    "http_request",
    "s3_upload_file",
    "s3_list_objects",
    "s3_download_file",
] as const;
