plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.v8executor'
version = '1.0.0'

android {
  namespace 'expo.modules.v8executor'
  defaultConfig {
    minSdkVersion 30
    versionCode 1
    versionName '1.0.0'
    testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
  }
}

dependencies {
  implementation 'com.squareup.okhttp3:okhttp:4.9.2'
  testImplementation 'junit:junit:4.13.2'
  androidTestImplementation 'androidx.test:runner:1.6.2'
  androidTestImplementation 'androidx.test.ext:junit:1.2.1'
}
